#pragma once

#define LOG_TYPE_DEBUG 0
#define LOG_TYPE_ERROR 1
#define LOG_TYPE_INFO 2
#define LOG_TYPE_WARNING 3

#define LOG_STATS_FPS 0
#define LOG_STATS_GPU_BUFFER 1
#define LOG_STATS_DRAW_CALLS 2
#define LOG_CRITICAL_RENDER_ERROR 3
#define LOG_PROGRAM_MVP 4
#define LOG_EDITOR 5